"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */

import { useEffect, useMemo, useState } from "react";
import { assets, capabilities, clients, collaborations, opportunities, povs, readiness, roadmap, technologies } from "../data/command-center";

const nav = ["Command Centre", "iLab Portfolio", "Client Pipeline", "AI Capabilities", "Assets", "Roadmap", "Ecosystem", "Insights"];
type Detail = { title: string; eyebrow: string; description: string; tags?: string[]; rows?: [string, string][]; related?: string[] };

function Drawer({ detail, close }: { detail: Detail | null; close: () => void }) {
  useEffect(() => { const f = (e: KeyboardEvent) => e.key === "Escape" && close(); document.addEventListener("keydown", f); return () => document.removeEventListener("keydown", f); }, [close]);
  return <><button className={`drawer-backdrop ${detail ? "open" : ""}`} onClick={close} aria-label="Close detail"/><aside className={`intelligence-drawer ${detail ? "open" : ""}`}>{detail && <><button className="close" onClick={close} aria-label="Close">×</button><span className="eyebrow">{detail.eyebrow}</span><h2>{detail.title}</h2><div className="drawer-tags">{detail.tags?.map(t => <span className="tag" key={t}>{t}</span>)}</div><p className="drawer-lead">{detail.description}</p><div className="detail-rows">{detail.rows?.map(([l, v]) => <div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>{detail.related && <><span className="eyebrow related-label">RELATED ENTITIES</span><div className="related-list">{detail.related.map(r => <span key={r}>{r}</span>)}</div></>}</>}</aside></>;
}
const detailFor = (title: string, eyebrow: string, description: string, rows: [string, string][], related?: string[]): Detail => ({ title, eyebrow, description, rows, related, tags: ["Editable profile", "Local data"] });
function Metric({ label, value, tone = "blue" }: { label: string; value: number | string; tone?: string }) { return <div className="metric"><span>{label}</span><strong className={tone}>{value}</strong></div>; }
function Header({ page, setPage, edit, setEdit }: any) { return <header className="topbar"><button className="brand" onClick={() => setPage("Command Centre")}><span className="brand-mark">i</span><span><b>iLAB</b><small>AI COMMAND CENTRE</small></span></button><div className="top-status"><i/> LIVE OPERATING VIEW <span>•</span> SYNTHETIC DATA</div><button className={`edit-toggle ${edit ? "on" : ""}`} onClick={() => setEdit(!edit)}>✦ {edit ? "EDIT MODE ON" : "EDIT MODE"}</button></header>; }
function PageHeader({ eyebrow, title, copy, action }: any) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div>; }

export default function Home() {
  const [page, setPage] = useState("Command Centre"); const [detail, setDetail] = useState<Detail | null>(null); const [edit, setEdit] = useState(false); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All clients"); const [notes, setNotes] = useState("");
  const filtered = useMemo(() => opportunities.filter(o => (filter === "All clients" || clients.find(c => c.id === o.clientId)?.name === filter) && `${o.name} ${o.currentPosition}`.toLowerCase().includes(search.toLowerCase())), [filter, search]);
  const high = opportunities.filter(o => o.probability === "High").length; const presented = assets.filter(a => a.presentedToClients).length;
  return <div className="app"><Header page={page} setPage={setPage} edit={edit} setEdit={setEdit}/><div className="app-shell"><aside className="sidebar"><div className="side-label">OPERATING SYSTEM</div>{nav.map((n, i) => <button className={page === n ? "active" : ""} key={n} onClick={() => setPage(n)}><span>0{i + 1}</span>{n}{n === "Client Pipeline" && <em>{opportunities.length}</em>}</button>)}<div className="sidebar-bottom"><div className="side-label">MODEL STATE</div><div className="state-card"><i/> DATA LAYER READY<strong>v0.1 · LOCAL STORAGE</strong></div><p>iLab AI Command Centre<br/>Executive demonstration environment</p></div></aside><main className="content">{page === "Command Centre" && <Command open={setDetail} setPage={setPage} high={high} presented={presented}/>} {page === "iLab Portfolio" && <Portfolio open={setDetail}/>} {page === "Client Pipeline" && <Pipeline open={setDetail} filtered={filtered} clients={clients} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch}/>} {page === "AI Capabilities" && <Capabilities open={setDetail}/>} {page === "Assets" && <Assets open={setDetail} search={search} setSearch={setSearch}/>} {page === "Roadmap" && <Roadmap open={setDetail}/>} {page === "Ecosystem" && <Ecosystem open={setDetail}/>} {page === "Insights" && <Insights open={setDetail} edit={edit} notes={notes} setNotes={setNotes}/>}</main></div><Drawer detail={detail} close={() => setDetail(null)}/></div>;
}

function Command({ open, setPage, high, presented }: any) { const nodes = [{ n: "POVs", s: "5 perspectives" }, { n: "Capabilities", s: "4 squads" }, { n: "Global Assets", s: "4 methods" }, { n: "Internal Assets", s: "7 solutions" }, { n: "Technology", s: "3 foundations" }]; return <><PageHeader eyebrow="01 / EXECUTIVE PICTURE" title="iLab AI Command Centre" copy="Turning AI capability, assets and market opportunities into scalable client outcomes." action={<button className="primary" onClick={() => setPage("Client Pipeline")}>VIEW PIPELINE →</button>}/><section className="signal-grid"><Metric label="ACTIVE CLIENTS" value={clients.length}/><Metric label="HIGH-PROBABILITY OPPORTUNITIES" value={high} tone="green"/><Metric label="AI ASSETS AVAILABLE" value={assets.length}/><Metric label="PRESENTED TO CLIENTS" value={presented} tone="violet"/><Metric label="CRITICAL CONSTRAINTS" value={readiness.filter(r => r.status === "Critical").length} tone="orange"/></section><section className="section-block"><div className="section-head"><div><span className="eyebrow">CONTROL SURFACE</span><h2>What moves the system</h2></div><span className="muted">CLICK A PILLAR TO OPEN INTELLIGENCE</span></div><div className="orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core"><span/>iLAB<strong>AI ENGINE</strong></div>{nodes.map((x, i) => <button className={`orbit-node node-${i}`} key={x.n} onClick={() => open(detailFor(x.n, "ECOSYSTEM PILLAR", `${x.n} are a connected part of the iLab delivery engine.`, [["Role", "CLIENT DEMAND → DELIVERY"], ["State", "Editable placeholder"], ["Next action", "Assign an owner"]]))}><i/ ><strong>{x.n}</strong><span>{x.s}</span></button>)}</div></section><section className="section-block two-col"><div><div className="section-head"><div><span className="eyebrow">DELIVERY CHAIN</span><h2>From demand to reusable IP</h2></div></div><div className="flow">{["CLIENT DEMAND", "OPPORTUNITIES", "CAPABILITIES", "ASSETS + TECH", "DELIVERY", "REUSABLE IP"].map((x, i) => <div key={x}><span>0{i + 1}</span><b>{x}</b>{i < 5 && <i>→</i>}</div>)}</div></div><div className="insight-card"><span className="eyebrow">SYSTEM INSIGHT</span><h3>{high} high-probability opportunities currently active</h3><p>Derived from the opportunity layer. Client maturity remains unassessed until evidence is entered.</p><button onClick={() => setPage("Insights")}>OPEN INSIGHTS ↗</button></div></section></>; }

function Portfolio({ open }: any) { const groups = [{ t: "POVs", d: "Strategic perspectives and frameworks to define, govern and maximize AI value.", items: povs }, { t: "CAPABILITIES", d: "Specialized expertise and delivery capabilities to accelerate AI execution.", items: capabilities.map(c => c.name) }, { t: "GLOBAL ASSETS", d: "Proven global methodologies, frameworks and accelerators brought into HK.", items: ["Trusted AI", "SMEs Connection", "Ways of Working", "Global Glossary"] }, { t: "INTERNAL ASSETS", d: "Internally developed solutions designed to enhance operations.", items: assets.filter(a => a.category === "Internal asset").map(a => a.name) }, { t: "TECHNOLOGY", d: "Foundational platforms and data capabilities for scaled AI delivery.", items: technologies }]; return <><PageHeader eyebrow="02 / PORTFOLIO" title="What we have been up to" copy="Progressive disclosure across perspectives, capabilities, assets and technology."/><div className="portfolio-grid">{groups.map(g => <section className="portfolio-card" key={g.t}><span className="eyebrow">{g.t}</span><p>{g.d}</p><div className="item-list">{g.items.map((x: string) => <button key={x} onClick={() => open(detailFor(x, g.t, g.d, [["Owner", "[Assign owner]"], ["Maturity", "[Set maturity]"], ["Client relevance", "[Add relevance]"]]))}><span>{x}</span>↗</button>)}</div></section>)}</div></>; }

function Pipeline({ open, filtered, clients, filter, setFilter, search, setSearch }: any) { return <><PageHeader eyebrow="03 / CLIENT DEMAND" title="Client Pipeline" copy="An intelligence portfolio for turning demand into connected propositions."/><div className="toolbar"><input value={search} onChange={(e: any) => setSearch(e.target.value)} placeholder="Search clients or opportunities…"/><select value={filter} onChange={(e: any) => setFilter(e.target.value)}><option>All clients</option>{clients.map((c: any) => <option key={c.id}>{c.name}</option>)}</select><span className="muted">{filtered.length} OPPORTUNITIES IN VIEW</span></div><div className="client-grid">{clients.map((c: any) => { const os = filtered.filter((o: any) => o.clientId === c.id); return <button className="client-card" key={c.id} onClick={() => open(detailFor(c.name, "CLIENT INTELLIGENCE", `${c.industry} · ${c.geography}. Maturity has not been assessed; enter values in edit mode when evidence is available.`, [["Current focus", c.focus], ["Opportunities", String(os.length)], ["AI maturity", "Assessment required"], ["Relationship", c.relationship]], os.map((o: any) => o.name)))}><div className="client-top"><span className="logo">{c.name.slice(0, 2)}</span><i/></div><h3>{c.name}</h3><span className="client-industry">{c.industry} · {c.geography}</span><div className="client-focus">{c.focus}</div><div className="client-foot"><span>{os.length} OPPORTUNITIES</span><span>MATURITY: NOT ASSESSED</span></div></button>})}</div><section className="section-block"><div className="section-head"><div><span className="eyebrow">OPPORTUNITY MATRIX</span><h2>Commercial signal map</h2></div><span className="muted">X: AI MATURITY · Y: ENGAGEMENT MATURITY</span></div><div className="matrix">{filtered.slice(0, 10).map((o: any, i: number) => <button key={o.id} style={{ left: `${8 + (i * 19) % 82}%`, bottom: `${12 + (i * 23) % 70}%` }} onClick={() => open(detailFor(o.name, "OPPORTUNITY", o.currentPosition, [["Client", clients.find((c: any) => c.id === o.clientId)?.name || ""], ["Probability", o.probability], ["Owner", o.owner], ["Next action", o.nextAction]], [...o.capabilityIds, ...o.assetIds]))}><i/><span>{o.name}</span></button>)}</div></section></>; }

function Capabilities({ open }: any) { return <><PageHeader eyebrow="04 / DELIVERY ENGINE" title="Capability Readiness" copy="The constraints between client demand and repeatable delivery."/><div className="readiness-grid">{readiness.map(r => <button key={r.id} onClick={() => open(detailFor(r.name, "CAPABILITY CONSTRAINT", r.description, [["Status", r.status], ["Gap", "[Add evidence]"], ["Required action", r.need], ["Target state", "Ready"]]))}><span className="eyebrow">{r.status}</span><h3>{r.name}</h3><p>{r.description}</p><small>{r.need}</small></button>)}</div><div className="capability-grid">{capabilities.map(c => <button className="capability-card" key={c.id} onClick={() => open(detailFor(c.name, "CAPABILITY", c.description, [["Owner", c.owner], ["Maturity", c.maturity], ["Gap", c.gap], ["Action", c.action]], opportunities.filter(o => o.capabilityIds.includes(c.id)).map(o => o.name)))}><span className="eyebrow">{c.status}</span><h3>{c.name}</h3><p>{c.description}</p><b>↗</b></button>)}</div></>; }

function Assets({ open, search, setSearch }: any) { const shown = assets.filter(a => `${a.name} ${a.category}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="05 / REUSABLE IP" title="Asset Marketplace" copy="A living inventory of the solutions, methods and reusable IP behind delivery."/><div className="toolbar"><input value={search} onChange={(e: any) => setSearch(e.target.value)} placeholder="Search the asset layer…"/><span className="muted">{shown.length} ASSETS · {shown.filter((a: any) => a.presentedToClients).length} CLIENT-FACING</span></div><div className="asset-grid">{shown.map((a: any) => <button className="asset-card" key={a.id} onClick={() => open(detailFor(a.name, a.category, a.description, [["Status", a.status], ["Maturity", a.maturity], ["Presented to clients", a.presentedToClients ? "Yes" : "No"], ["Client applicability", `${a.relatedClientIds.length} linked clients`], ["Technology", "[Add technology]"]], a.relatedClientIds.map((id: string) => clients.find(c => c.id === id)?.name || id)))}><div className="asset-icon">{a.name.slice(0, 1)}</div><span className="eyebrow">{a.category}</span><h3>{a.name}{a.presentedToClients && <sup>*</sup>}</h3><p>{a.description}</p><div className="asset-meta"><span>{a.status}</span><span>{a.relatedClientIds.length} CLIENTS</span></div></button>)}</div></>; }

function Roadmap({ open }: any) { const periods = ["2026 Q3", "2026 Q4", "2027 H1"]; return <><PageHeader eyebrow="06 / STRATEGIC HORIZON" title="Roadmap" copy="The sequence from capability build to market activation."/><div className="roadmap"><div className="period-row"><span/>{periods.map(p => <strong key={p}>{p}</strong>)}</div>{["Market", "Technology", "Our People"].map(stream => <div className={`lane lane-${stream.toLowerCase().replace(" ", "-")}`} key={stream}><strong className="lane-label">{stream}</strong>{periods.map(period => <div className="lane-cell" key={period}>{roadmap.filter(r => r.stream === stream && r.period === period).map(item => <button key={item.id} onClick={() => open(detailFor(item.name, `${item.stream} · ${item.period}`, "Objective and delivery detail to be completed by the accountable owner.", [["Status", item.status], ["Progress", `${item.progress}%`], ["Owner", "[Assign owner]"], ["Dependencies", "[Add dependencies]"], ["Risk / blocker", "[Add blocker]"]]))}>{item.name}</button>)}</div>)}</div>)}</div></>; }

function Ecosystem({ open }: any) { return <><PageHeader eyebrow="07 / RELATIONSHIP GRAPH" title="Collaboration Ecosystem" copy="The people, teams and communities that extend iLab's delivery engine."/><div className="ecosystem"><div className="eco-core">iLAB<span>CONNECTED ENGINE</span></div>{collaborations.map((c, i) => <button className={`eco-node eco-${i}`} key={c.id} onClick={() => open(detailFor(c.name, c.group, c.relationship, [["Current collaboration", c.relationship], ["Contribution", c.contribution], ["Markets", c.markets], ["People / team", "[Add people]"]]))}><i/><b>{c.name}</b><small>{c.group}</small></button>)}</div></>; }

function Insights({ open, edit, notes, setNotes }: any) { const items = [`${opportunities.filter(o => o.probability === "High").length} high-probability opportunities currently active`, `${opportunities.filter(o => o.capabilityIds.includes("actuarial-fpa")).length} opportunities depend on actuarial / FP&A capability`, `${opportunities.filter(o => o.assetIds.length > 0).length} opportunities have a linked iLab asset`, `${assets.filter(a => a.presentedToClients).length} assets have already been presented to clients`]; return <><PageHeader eyebrow="08 / DECISION SUPPORT" title="Executive Insights" copy="Derived from the stored iLab data layer. Claims update as the data changes."/><div className="insight-grid">{items.map((x, i) => <article className="big-insight" key={x}><span>0{i + 1}</span><h2>{x}</h2><small>SUPPORTED BY CURRENT DATA MODEL</small></article>)}</div><section className="section-block"><div className="section-head"><div><span className="eyebrow">OPERATING NOTES</span><h2>What should leadership know?</h2></div></div><div className="notes"><textarea disabled={!edit} value={notes} onChange={(e: any) => { setNotes(e.target.value); localStorage.setItem("ilab-note", e.target.value); }} placeholder={edit ? "Add a leadership note…" : "Enable edit mode to add local notes."}/><button onClick={() => open(detailFor("Insight provenance", "DATA LINEAGE", "Every insight above is derived from the local TypeScript data layer. Client maturity remains explicitly unassessed until evidence is entered.", [["Storage", "Local data + localStorage notes"], ["Next step", "Connect a backend when the schema is stable"]]))}>VIEW DATA LINEAGE ↗</button></div></section></>; }
