"use client";

import { useState } from "react";
import { assets, capabilities, clients, collaborations, opportunities, povs, readiness, roadmap } from "../data/command-center";

const sections = ["Overview", "Portfolio", "Pipeline", "Readiness", "Roadmap", "Ecosystem", "Insights", "What we need"];
function jump(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
function Logo({ name, index }: { name: string; index: number }) { return <span className={`logo logo-${index}`}>{name.slice(0, 2)}</span>; }
function Detail({ title, text, close }: { title: string; text: string; close: () => void }) { return <><button className="drawer-backdrop open" onClick={close} aria-label="Close detail"/><aside className="intelligence-drawer open"><button className="close" onClick={close} aria-label="Close">×</button><span className="eyebrow">INTELLIGENCE DETAIL</span><h2>{title}</h2><p className="drawer-lead">{text}</p><div className="detail-rows"><div><span>OWNER</span><strong>[Assign owner]</strong></div><div><span>STATUS</span><strong>Editable placeholder</strong></div><div><span>NEXT ACTION</span><strong>[Add next action]</strong></div></div></aside></>; }

export default function Presentation() {
  const [detail, setDetail] = useState<{ title: string; text: string } | null>(null);
  const high = opportunities.filter(o => o.probability === "High").length;
  return <div className="presentation"><header className="presentation-nav"><button className="brand" onClick={() => jump("overview")}><span className="brand-mark"/><span><b>iLAB</b><small>AI STRATEGY HUB</small></span></button><nav>{sections.map((s, i) => <button key={s} onClick={() => jump(s.toLowerCase())}><span>0{i + 1}</span>{s}</button>)}</nav><span className="presentation-status"><i/> LIVE STRATEGY VIEW</span></header><main>
    <section id="overview" className="presentation-hero"><span className="eyebrow">iLAB / CONNECTED AI OPERATING MODEL</span><h1>Strategy, capability<br/><em>and demand in one view.</em></h1><p>Turning AI capability, reusable assets and market opportunities into scalable client outcomes.</p><button className="hero-jump" onClick={() => jump("portfolio")}>EXPLORE THE SYSTEM ↓</button></section>
    <section className="presentation-section" id="portfolio"><div className="section-head"><div><span className="eyebrow">01 / PORTFOLIO</span><h2>What iLab brings to the table</h2></div><span className="muted">SCROLL TO REVEAL</span></div><div className="pillar-grid">{[{t:"POVs",n:povs.length,d:"Strategic perspectives and frameworks."},{t:"Capabilities",n:capabilities.length,d:"Specialist delivery expertise."},{t:"Global Assets",n:4,d:"Proven global methods and accelerators."},{t:"Internal Assets",n:assets.length - 1,d:"Reusable solutions built inside iLab."},{t:"Technology",n:3,d:"Foundations for scaled delivery."}].map(x => <button key={x.t} onClick={() => setDetail({ title: x.t, text: x.d })}><strong>{String(x.n).padStart(2,"0")}</strong><h3>{x.t}</h3><p>{x.d}</p><span>OPEN INTELLIGENCE ↗</span></button>)}</div></section>
    <section className="presentation-section" id="pipeline"><div className="section-head"><div><span className="eyebrow">02 / CLIENT DEMAND</span><h2>The opportunity landscape</h2></div><span className="muted">{clients.length} CLIENTS · {opportunities.length} THREADS</span></div><div className="presentation-client-grid">{clients.map((client, i) => { const os = opportunities.filter(o => o.clientId === client.id); return <button className="presentation-client" key={client.id} onClick={() => setDetail({ title: client.name, text: `${client.industry} · ${client.geography}. Current focus: ${client.focus}. AI maturity remains not assessed until evidence is added.` })}><Logo name={client.name} index={i}/><div><h3>{client.name}</h3><span>{client.industry}</span></div><b>{os.length}</b><small>OPPORTUNITIES</small><p>{client.focus}</p></button>; })}</div><div className="opportunity-strip">{opportunities.slice(0, 6).map(o => <button key={o.id} onClick={() => setDetail({ title: o.name, text: o.currentPosition })}><span>{o.probability}</span><strong>{o.name}</strong><small>{clients.find(c => c.id === o.clientId)?.name}</small>↗</button>)}</div></section>
    <section className="presentation-section" id="readiness"><div className="section-head"><div><span className="eyebrow">03 / DELIVERY ENGINE</span><h2>The maturity gap</h2></div><span className="muted">CURRENT STATE → TARGET STATE</span></div><div className="gap-grid">{readiness.map(r => <button key={r.id} onClick={() => setDetail({ title: r.name, text: `${r.description} Required action: ${r.need}` })}><span className={`gap-status ${r.status.toLowerCase().replaceAll(" ","-")}`}>{r.status}</span><h3>{r.name}</h3><p>{r.description}</p><div className="gap-line"><i/><span>{r.need}</span></div></button>)}</div></section>
    <section className="presentation-section" id="roadmap"><div className="section-head"><div><span className="eyebrow">04 / STRATEGIC HORIZON</span><h2>From intention to execution</h2></div><span className="muted">2026 Q3 → 2027 H1</span></div><div className="story-roadmap">{["Market","Technology","Our People"].map(stream => <div className="story-lane" key={stream}><strong>{stream}</strong>{roadmap.filter(r => r.stream === stream).map(item => <button key={item.id} onClick={() => setDetail({ title: item.name, text: `${item.period} · ${item.status}. Objective, owner and dependencies are editable in the intelligence model.` })}><span>{item.period}</span><b>{item.name}</b></button>)}</div>)}</div></section>
    <section className="presentation-section" id="ecosystem"><div className="section-head"><div><span className="eyebrow">05 / RELATIONSHIP GRAPH</span><h2>The network behind delivery</h2></div></div><div className="story-ecosystem"><div className="story-core">iLAB<span>CONNECTED ENGINE</span></div>{collaborations.map((c, i) => <button className={`story-node story-node-${i}`} key={c.id} onClick={() => setDetail({ title: c.name, text: `${c.relationship}. Contribution: ${c.contribution}. Markets: ${c.markets}.` })}><i/><b>{c.name}</b><small>{c.group}</small></button>)}</div></section>
    <section className="presentation-section" id="insights"><div className="section-head"><div><span className="eyebrow">06 / DECISION SUPPORT</span><h2>What the data is telling us</h2></div></div><div className="story-insights"><article><b>01</b><strong>{high} high-probability opportunities</strong><span>currently active in the pipeline</span></article><article><b>02</b><strong>{assets.filter(a => a.presentedToClients).length} client-facing assets</strong><span>available for reuse</span></article><article><b>03</b><strong>{readiness.filter(r => r.status === "Critical").length} critical constraints</strong><span>blocking repeatable delivery</span></article></div><div className="closing-statement">CLIENT DEMAND <i>→</i> CAPABILITIES <i>→</i> ASSETS <i>→</i> REUSABLE IP</div></section>
    <section className="presentation-section ask-section" id="what we need"><div className="section-head"><div><span className="eyebrow">07 / ENABLEMENT REQUEST</span><h2>What we need from you</h2><p className="section-intro">A small, controlled sandbox budget to turn promising demonstrations into repeatable delivery capability.</p></div><div className="budget-total"><span>MONTHLY SANDBOX BUDGET</span><strong>US$500</strong><small>CONFIGURABLE ASSUMPTION</small></div></div><div className="budget-swimlanes"><div className="budget-lane"><div><b>01</b><h3>Build tools</h3><span>Coding and prototyping</span></div><strong>$150</strong><p>Cursor, Codex and approved developer tooling to move from idea to working POC faster.</p><i style={{width:"30%"}}/></div><div className="budget-lane"><div><b>02</b><h3>Platform</h3><span>Sandbox and infrastructure</span></div><strong>$175</strong><p>Azure or equivalent workspace, environments and deployment foundations for safe iteration.</p><i style={{width:"35%"}}/></div><div className="budget-lane"><div><b>03</b><h3>AI usage</h3><span>Models and API calls</span></div><strong>$125</strong><p>Model inference, evaluations and API usage to make demos useful with realistic workflows.</p><i style={{width:"25%"}}/></div><div className="budget-lane"><div><b>04</b><h3>Delivery enablement</h3><span>Quality and adoption</span></div><strong>$50</strong><p>Documentation, testing, reusable templates and client-ready packaging around each asset.</p><i style={{width:"10%"}}/></div></div><div className="fuel-grid"><div><span className="eyebrow">WHAT THIS FUELS</span><h3>From best-effort lab work to a repeatable delivery engine.</h3></div><div className="fuel-points"><span><b>↑</b> Faster POC cycles</span><span><b>↑</b> More reusable code and assets</span><span><b>↑</b> Safer client demonstrations</span><span><b>↑</b> Stronger route to market</span></div></div></section>
  </main>{detail && <Detail title={detail.title} text={detail.text} close={() => setDetail(null)}/>}</div>;
}
